### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by Toub** [denehyg/reveal.js-menu#1]
Very good job.

What about making this plugin available via bower?
http://bower.io/docs/creating-packages/

By the way, I am using it with https://github.com/slara/generator-revealn by downloading manually the package, then adding the following configuration in templates/_index.html

    dependencies: [
        [...]
        { src: 'bower_components/reveal.js-menu/menu.js', async: true }
    ], menu: {
            path: 'bower_components/reveal.js-menu'
     }

**Comment by denehyg** [comment]
Sure thing. I'll jump on it when I next get the chance.

**Comment by Toub** [comment]
If you accept my pull request, you can then register the bower package: 

``` bower register reveal-js-menu https://github.com/denehyg/reveal.js-menu ```

http://bower.io/docs/creating-packages/#register
