### ISSUE TITLE
H1 titles

### ISSUE THREAD

**Issue by jmunoz298** [denehyg/reveal.js-menu#13]
Is it possible to include only level one (H1) titles?

**Comment by denehyg** [comment]
The default behaviour is to use the first heading element regardless of the heading level. If you want to specify a specific heading element you can use the `menu-title` class on the element, or set the `data-menu-title` attribute on the section element.

It is not unreasonable to expect that H1 elements would be used over other heading elements, but I'll need to give it some thought about how best to approach this.

**Comment by denehyg** [comment]
I've added a ```titleSelector``` option to the plugin. This provides the ability to specify which elements you want to be used for the titles. For example, setting ```titleSelector: 'h1'``` will only use level 1 titles. See the documentation for more details.
