### ISSUE TITLE
hideMissingTitles not hiding nested sections

### ISSUE THREAD

**Issue by chweeks** [denehyg/reveal.js-menu#14]
I'm looking to give sections their title with data-menu-title="" in order to display them in the menu. This works fine but even though I've set hideMissingTitles to true the nested sections still grab the first header within the subsection and display it. Is their anyway I can hide these subsections from the menu.

**Comment by denehyg** [comment]
Currently no. The hideMissingTitles option was intended to handle slides that have no title at all, so if you have header elements in your slides they will be used. I'll need to give it some thought, along with #13, as to how I should restructure the heading criteria to account for this use case.

**Comment by denehyg** [comment]
I've added a ```titleSelector``` option to the plugin. This provides the ability to specify which elements you want to be used for the titles. For this use case you can now use ```titleSelector: ''```, in conjunction with ```hideMissingTitles``` to remove slides from the menu that do not have ```data-menu-title``` attributes.
