### ISSUE TITLE
configuration to choose the position of menu button

### ISSUE THREAD

**Issue by niconil** [denehyg/reveal.js-menu#18]
by default the menu button is in left bottom corner
but when using reveal.js with autoslide there are two buttons one over the other

is it possible to add a configuration parameter to choose the location of the menu button ?

**Comment by denehyg** [comment]
This is simple enough to do with CSS. Just add the following inside the body...

```
<style>
  .reveal .slide-menu-button {
    right: 30px;
  }
</style>
```

You can put the button anywhere you want, for example if you want it in the top left corner...

```
<style>
  .reveal .slide-menu-button {
    left: 30px;
    top: 30px;
  }
</style>
```
