### ISSUE TITLE
Menu works on Android phone with Web browser, but not as phonegap app

### ISSUE THREAD

**Issue by sechrest** [denehyg/reveal.js-menu#20]
Following the instructions, I built a presentation using Reveal. I then added the menu. It works on my lap top. I deployed it at github.io and it works there. When I put that same respository thru build.phonegap.com, the resulting app has the navigation from reveal, but no hamberger menu. 

Any suggestions where to look to debug this?

**Comment by denehyg** [comment]
Sorry, I don't have any experience with phonegap. Not sure I can be of any help here.
