### ISSUE TITLE
Page Up/Down should navigate menu

### ISSUE THREAD

**Issue by aspiers** [denehyg/reveal.js-menu#21]
When the menu is long (some presentations can have > 50 or even 100 slides) then it would be useful if after pressing `m`, Page Up/Down would navigate the menu one page at a time.  Bonus points if `u` and `d` navigate by half a page, just like with `less(1)` ;-)

**Comment by denehyg** [comment]
Done. Committed to the dev branch. This should be good to go but if it doesn't behave as you would expect let me know.

**Comment by aspiers** [comment]
Works perfectly, thanks so much!!
