### ISSUE TITLE
Custom Menu external html not loading

### ISSUE THREAD

**Issue by sylvaintrias** [denehyg/reveal.js-menu#22]
Hi,

Inserting
`custom: [
			            {title: 'Links', icon: '<i class="fa fa-external-link">', src: 'links.html' }
			        ],`

Using Chrome, the browser reports a XMLHttpRequest failure, although my external html file is at the right place (root level, same as index.html). To be sure that it doesn't come from my links.html file, I replaced it by the one in the example page.

Thanks !

**Comment by rajgoel** [comment]
This is probably related to synchronous XMLHttpRequest which is deprecated. Would need to fix the plugin so that it uses asynchronous loading .

**Comment by denehyg** [comment]
This should be fixed by 81a99a7.
