### ISSUE TITLE
Menu disappearing on mobile.

### ISSUE THREAD

**Issue by mattdlmag** [denehyg/reveal.js-menu#26]
Help! The menu button that I put in my presentation disappears when i load it on my iphone, but it loads on my samsung. However, it does not scroll. It is in a stuck position. Any ideas why this is happening? thank you.

link to my presentation:

http://p.atlantic-packaging.com/Presentation/#/introduction

**Comment by denehyg** [comment]
This is most likely due to issue #27.

**Comment by denehyg** [comment]
This should be fixed in v0.7.1. Let me know if it works.
