### ISSUE TITLE
IE issues

### ISSUE THREAD

**Issue by cavie78** [denehyg/reveal.js-menu#3]
There seems to be an issue with IE. Menu.js *sometimes* loads correctly but frequently does not. When this occurs all named links appear as one big link. Clicking makes reveal try to load all slides on top of one another.

**Comment by denehyg** [comment]
Can you let me know what version of Windows and IE you are using. I've tested on IE9 and IE11 under Windows 7 and can't see the issue.

**Comment by cavie78** [comment]
Thanks for the quick response. I've tried IE11 on 7 (actually Server 2008 R2) and XP

**Comment by cavie78** [comment]
I think this was to do with the page load rather than any inherent problem with menu.js. Slimming down my site and loading the .js earlier seems to have solved the issue.
