### ISSUE TITLE
menu does not show up in Safari, only in Chrome.

### ISSUE THREAD

**Issue by fischcheng** [denehyg/reveal.js-menu#31]
Thanks for the great work. I've encountered an issue that I can access the menu on your live demo using Safari, but when it comes to my testing index.html, I can only access the menu through Chrome. I didn't change any options, just added the dependencies following README. 

Maybe the javascript or html5 engines behind Safari and Chrome are different? If that was the case, how could I see menu on the github hosted demo site, but not the local site using Safari? Thanks for your attention.

I tried installing menu both through npm and manually copying.

**Comment by denehyg** [comment]
Do you have any errors showing up in the console through the web inspector? I haven't seen this in my test environment under safari so I don't have much to work with here.

**Comment by denehyg** [comment]
Still works in Safari under my test environment. If this is still an issue feel free to reopen it.
