### ISSUE TITLE
Trigger menu via a normal link

### ISSUE THREAD

**Issue by jcamp** [denehyg/reveal.js-menu#35]
I know there is a way ...
Just want to trigger the menu from a link in text as well?

Cheers
Jonathan

**Comment by denehyg** [comment]
There's an undocumented API that can be used for this: `RevealMenu.toggle()` will open/close the menu, and `RevealMenu.isOpen()` will return `true` is the menu is currently open.

For example...
```
<a href="#" onclick="RevealMenu.toggle(); return false;">menu link</a>
```

**Comment by jcamp** [comment]
Ah! brilliant - exactly what I needed - thanks.
Cheers
Jonathan
