### ISSUE TITLE
Need a more detailed meaning in css config.

### ISSUE THREAD

**Issue by chxp** [denehyg/reveal.js-menu#38]
I want to change the small menu in other location (more bottom than the default), So which css  changes the location of the menu item (the icon when in show slides, not the side menu when click it )

**Comment by denehyg** [comment]
The slide menu button is can be modified by referencing `.reveal .slide-menu-button` in your own css. By default this is `position: fixed` and set to `left: 30px` and `bottom: 30px`. The easiest approach to changing the location is to override `left/right` and `top/bottom`.
