### ISSUE TITLE
Scrolling on Android phones 

### ISSUE THREAD

**Issue by cavie78** [denehyg/reveal.js-menu#4]
I've noticed a problem with menu scrolling on Android. The menu opens as expected and visible links work, but trying to scroll actually scrolls the slides in the background (i.e. the menu remains static). This is a problem on both Chrome and Firefox. Menu works fine on iOS on Chrome and Safari.

**Comment by rajgoel** [comment]
I also noted that 2 finger scrolling on desktop browsers (Firefox and Chrome) scrolls both the menu **and** the slides in the background.

**Comment by denehyg** [comment]
Fixed in 9d733f62ca90083e99784f4efc2ccdd21ddbccd7. Will be part of 1.0 release.
