### ISSUE TITLE
Is it possible to not load "font-awesome"

### ISSUE THREAD

**Issue by cavo789** [denehyg/reveal.js-menu#41]
Hi Greg

Thanks for this great plugin !

When using it, the debug console show me a 404 request to "my_site/reveal.js-menu/font-awesome-4.3.0/css/font-awesome.min.css" and, indeed, I've not take that subdirectory because I already load font-awesome elsewhere in my application.

My question : is it possible to have an option to specify "No, don't try to load the font" ?

The line https://github.com/denehyg/reveal.js-menu/blob/master/menu.js#L16 seems to force the loading.

Thanks !

**Comment by denehyg** [comment]
I've added a `loadIcons` option in the `dev` branch (ca1f9f94db95bfd4ea6b385916bfa6fbae56265c). Just set `loadIcons: false` within the menu options in your presentation and the menu will not try to load font-awesome for itself.

**Comment by cavo789** [comment]
Wonderfull ! Fast answer and great solution ! Tested and approved ;)

Thanks Greg.
