### ISSUE TITLE
Menu is broken if called with ?print-pdf

### ISSUE THREAD

**Issue by dstadelm** [denehyg/reveal.js-menu#42]
I tried to install the menu so I could switch to a white theme from a black theme. I followed the instructions on the main reveal.js site which states that the presentation has to run in server mode and the print-pdf should be included in the query string. 

Doing so breaks the menu plugin....

**Comment by denehyg** [comment]
The menu plugin was not designed to work with pdf-print, and it doesn't make a lot of sense to use it for printing anyway. I've hidden the menu for pdf-print in 26e7d05.

If you want your presentation to print with a particular theme then I suggest it's best to change the theme directly in the html file.
