### ISSUE TITLE
menu fails to load when added to slides.com generated slides

### ISSUE THREAD

**Issue by yarko** [denehyg/reveal.js-menu#45]
I'm just logging this for now -

Adding reveal.js-menu to slides generated by slides.com doesn't work / menu doesn't load.

To get it to work, I needed to:

- modify the Reveal.initialize  dependencies to include async:
  - `{ src: 'lib/reveal-plugins/menu/menu.js', async: true },`
- remove references in `menu.js` to `head.browser.ie` - which were causing errors which prevented loading;

The last item needs a bit more looking, as this did not seem to be an issue when adding menus to presentations generated by reveal-md, or [fab setup.revealjs](https://github.com/theno/fabsetup/blob/master/howtos/revealjs.md).

**Comment by denehyg** [comment]
I haven’t tried this on slides.com. It seems they don’t use reveal.js directly but presumably use a bundler for the dependencies (at least for slides delivered through slides.com - not sure about exported presentations). This plugin relies on the presentation HTML loading the `head` library that is also used by reveal. I would assume that it should work if you add the head library to the HTML (ensuring it loads before the menu plugin).

When I find some time I might look at bundling the head library into the plugin to remove the requirement on the presentation supplying it.

**Comment by jcamp** [comment]
Would be good to get this in sync with slides.com as it's used a lot :)

**Comment by denehyg** [comment]
I've pushed an update (v0.9.3) that removes the menu plugin's dependency on the `head` library, so this should be fixed. All that should be required is to add the menu to the Reveal dependencies as usual...

```
Reveal.initialize({
	// ...	
	dependencies: [
		// ... 	  
		{ src: 'path/to/menu/menu.js' }
	]
});
```

I've tested this, but it would be appreciated if you could test this in your own exported presentations and let me know if it works so I can close this issue.

**Comment by denehyg** [comment]
I'm assuming I can close this now.
