### ISSUE TITLE
Open links to external urls from the standard sections

### ISSUE THREAD

**Issue by jcamp** [denehyg/reveal.js-menu#48]
Is there a way to make a menu item just a link to an external url?

By that I mean embed in the main menu structure a menu item that when clicked just opens the url (new tab preferably)?

Sounds easy but with the section structure I could not find a simple way to do this and do not want to load a list of links into another menu.

**Comment by denehyg** [comment]
No, and I don't think this fits the purpose of the slides menu. You can setup your own custom panel with whatever content you want to provide externals links, etc.

You could write some code to insert your own items in the menu after it has been initialised. Wait on the `menu-ready` event, then insert...

```
<li class="slide-menu-item" data-item="...">
    <a href="https://github.com/hakimel/reveal.js" target="_blank">Reveal.js</a>
</li>
```
into the menu structure where you want it. You'll need to set the `data-item` value to the correct sequential number in the menu, and increment all the items following.
