### ISSUE TITLE
'TypeError: ref is undefined' on version 1.1.1

### ISSUE THREAD

**Issue by zarthross** [denehyg/reveal.js-menu#51]
I get the following error message in my console on FF using version v1.1.1 of reveal.js-menu with a fresh copy of reveal-js version 3.6.0 when i click 'Themes' in the menu
```
TypeError: ref is undefined[Learn More]
menu.js:366:6
openPanel
http://localhost:8000/node_modules/reveal.js-menu/menu.js:366:6
```

Error occurs on the last line of this block 
```
function openPanel(event, ref) {
				openMenu(event);
				var panel = ref;
				if (typeof ref !== "string") {
					panel = ref.currentTarget.getAttribute('data-panel');
.........
```

**Comment by omegerard** [comment]
I've got the same issue. With any custom menu I want to add (links, downloads, etc ...) - via 'content' or 'src'.

**Comment by denehyg** [comment]
Fixed in dev branch
