### ISSUE TITLE
Support for Font Awesome 5 SVG with JS framework

### ISSUE THREAD

**Issue by gcalmettes** [denehyg/reveal.js-menu#54]
Font Awesome 5 introduced a new [SVG with Javascript](https://fontawesome.com/how-to-use/svg-with-js) framework. When this framework is used, the `<i>` tags are replaced with `<svg>` tags to render the icons.

The current css styles provided for this plugins are not applied when the SVG with JS framework is used since they are targeted to `<i>` tags only.
I opened a PR to extend the CSS styles to SVG.

![Imgur](https://i.imgur.com/DDmQ0u6.png)

**Comment by denehyg** [comment]
Thanks for this. I've merged the PR and also handled sizing for icons used in the toolbar. Released under v1.1.3.

**Comment by gcalmettes** [comment]
Thanks a lot! I'll update my dependencies with the new version!
