### ISSUE TITLE
update options doc

### ISSUE THREAD

**Issue by clayt85** [denehyg/reveal.js-menu#57]
Two things I have noticed:

The "themes" configuration option is true by default (not false, as indicated in the docs).

Also, there is a "transitions" configuration option that functions just like "themes", but is not documented.

**Comment by denehyg** [comment]
Which version of the plugin are you using? Note that the defaults for themes and transitions options changed at v1.0.0. They used to be enabled by default but now they need to be explicitly enabled in the options. If you are using a plugin version numbe earlier than 1.0.0 then the docs on github will not match.

**Comment by clayt85** [comment]
It appears that you have a point :-) My apologies.

FWIW, I am using the [reveal.js-plugins](https://github.com/rajgoel/reveal.js-plugins/) library, which includes reveal.js-menu as a submodule.  That submodule is currently pointing to commit 97d8561 (tag: 0.6.0).

So the "wrong defaults" comment should be ignored.  But it does seem like "missing 'transitions' doc" is still valid?

**Comment by clayt85** [comment]
Indeed.  I can't even find what I was looking at now...  Thanks for taking the time to respond.
