### ISSUE TITLE
Uncaught TypeError: Reveal.addKeyBinding is not a function

### ISSUE THREAD

**Issue by DV-JF** [denehyg/reveal.js-menu#58]
The menu is working, console says:

```
Uncaught TypeError: Reveal.addKeyBinding is not a function
    at loadPlugin (menu.js:849)
    at HTMLLinkElement.finish (menu.js:899)
```

**Comment by denehyg** [comment]
v1.2.0 was updated to use the key binding API introduced to Reveal.js v3.7.0 and requires this version. I’ll have a look at fixing this for backwards compatibility when I get the chance, but in the meantime either use an earlier version of the menu plugin or use v3.7.0 of reveal.

**Comment by DV-JF** [comment]
@denehyg Thank you for your response! Switching to Reveal.js v3.7.0 isn't an option for me, cause other things will break :-/ 
So, I'll have to downgrade menu.js - thx for the hint!

**Comment by CJohnDesign** [comment]
I got this on 4.0...

**Comment by CJohnDesign** [comment]
Ran this in componentDidMount `Reveal.addKeyBinding( 32, () => {
      this.handlePlay()
    } )`
