### ISSUE TITLE
Custom menu styling

### ISSUE THREAD

**Issue by rajgoel** [denehyg/reveal.js-menu#6]
Hi Greg,

thanks for the super fast merge of #5. It appears that your changes in styling of cutom panels created some issue when trying to create a menu with similar look-and-feel as the original menu.

This custom menu content

```
<ul class="slide-menu-items">
<li class="slide-menu-item"><a href="00 - Introduction.html" target="_blank" style="text-decoration:none">Introduction</a></li>
<li class="slide-menu-item"><a href="01 - Notation.html" target="_blank" style="text-decoration:none">Notation</a></li>
<li class="slide-menu-item"><a href="02 - Sets.html" target="_blank" style="text-decoration:none">Sets</a></li>
</ul>
```
looks like this

![screenshot from 2015-09-05 11 36 26](https://cloud.githubusercontent.com/assets/4448455/9698710/76ff7b0c-53c2-11e5-934b-aa41964c3138.png)

As you can see, the background highlighting is shifted to the right. It looked ok before 8227b0cc8f0e0883227146fd5f8c775587204af9. Any idea how to best fix this?

Cheers
Asvin

**Comment by denehyg** [comment]
Yeah, I'm part way through thinking about how slide-menu-items should be handled in custom panels. I've pushed a styling fix that addresses the issue above. I still need to consider how these links are handled with the keyboard interaction, but at least they should appear correct now.

**Comment by rajgoel** [comment]
Great, thanks!

**Comment by rajgoel** [comment]
I just realised that the new ```hideMissingTitles``` broke proper keyboard interaction (i.e. up/down across missing slide titles does not work).

**Comment by denehyg** [comment]
Thanks. I'll check it out.

**Comment by denehyg** [comment]
Hey @rajgoel, I've just pushed changes that should finalise the custom panels with some styling fixes and support for keyboard navigation. Let me know if there are any other issues with it.

**Comment by denehyg** [comment]
@rajgoel, #7 has been fixed so keyboard navigation should be working again when using ```hideMissingTitles```. Let me know if there are still any issues.
