### ISSUE TITLE
Vertical slides broken

### ISSUE THREAD

**Issue by hypery2k** [denehyg/reveal.js-menu#60]
When having vertical slides the numbering is broken:
```
 <section >
                <section><h2>Vertical Slide 1</h2>Vertical Slide 1</section>
                <section><h2>Vertical Slide 2</h2>Vertical Slide 2</section>
            </section>
```

![image](https://user-images.githubusercontent.com/979121/60314158-f43c9800-9961-11e9-97a9-7d5b024f3e37.png)

But it should be:

![image](https://user-images.githubusercontent.com/979121/60314171-00285a00-9962-11e9-93e7-d0f9d2f95bad.png)

**Comment by denehyg** [comment]
The slide numbering scheme matches what reveal.js uses so the first slide is supposed to be 5.1.
