### ISSUE TITLE
Bug in IE11

### ISSUE THREAD

**Issue by clayt85** [denehyg/reveal.js-menu#63]
I'm running into a bug in IE11, which does not implement the endsWith().  Issue and fix (which I have not tested) appears to be here:

https://stackoverflow.com/questions/29434868/script438-object-doesnt-support-property-or-method-endswith-in-ie10

Has anyone else run into this?

**Comment by clayt85** [comment]
Update: I can now confirm that the linked (above) fix does solve the issue.  A direct link to the specific fix I implemented is:

https://stackoverflow.com/a/40732004/3570092

I'm happy to clone/patch/PR, but will wait to hear from a dev before I start.

**Comment by denehyg** [comment]
Which version were you using? The endsWith() polyfill was added in v1.0.1 so everything should be working if your version is up to date. I'm closing this but if you're still having issues let me know.
