### ISSUE TITLE
TypeError: Reveal.getConfig is not a function (menu.js)

### ISSUE THREAD

**Issue by its-thomas** [denehyg/reveal.js-menu#64]
Hi there,

I was trying to add your fantastic plugin to the latest Reveal.js version 4.0.0 by downloading the latest files from your github and initializing them in my presentation to the best of my abilities. Unfortunately, it doesn't seem to work, console output is "TypeError: Reveal.getConfig is not a function" regarding your menu.js file.

Can you help me out here?

Thanks a lot in advance,
Thomas

**Comment by KRostyslav** [comment]
the same

**Comment by KRostyslav** [comment]
@its-thomas But for me works this solution
`				dependencies: [
					// ... 
				
					{ src: 'plugin/menu/menu.js' }
				],`
and I copied this plugin in folder **plugin**

**Comment by its-thomas** [comment]
@KRostyslav Thanks for helping out! Could you please list step by step which changes to make?
Because as far as I understand, the initialization in the HTML file should be with this

`<script src="plugin/menu/menu.js"></script>`

and with

`Reveal.initialize({
				plugins: [ RevealMenu ]
			});`

**Comment by KRostyslav** [comment]
@its-thomas you don't need to initialize this plugin and don't add script...  only put that  in dependency 
[https://imgur.com/98bxJqa](url)

**Comment by its-thomas** [comment]
@KRostyslav Adding the line

`dependencies: [ { src: 'plugin/menu/menu.js' } ],`

just like in your screenshot [https://imgur.com/98bxJqa](https://imgur.com/98bxJqa) solved the issue for me as well!

Thanks a lot!

**Comment by KRostyslav** [comment]
@its-thomas you welcome

**Comment by denehyg** [comment]
The plugin has now been updated to v2.0.0 adding support for reveal.js v4. With the v2.0 release you'll need to use:

```
<script src="plugin/menu/menu.js"></script>
<script>
  Reveal.initialize({
    plugins: [ RevealMenu ]
  });
</script>
```
