### ISSUE TITLE
Changing the Code Syntax Highlighting Theme

### ISSUE THREAD

**Issue by jamespascoe** [denehyg/reveal.js-menu#65]
Hi everybody,

Thank you very much for the reveal.js menu plugin - its absolutely great and is exactly what I need - thanks.

Apologies if this has been answered elsewhere, but is there any way to change the code syntax highlighting theme when selecting a different theme in the theme panel? In particular, I would like to use monokai.css when using the 'Black' theme (i.e. the default) and then switch to (for example) <a href=https://github.com/highlightjs/highlight.js/blob/master/src/styles/xcode.css>Xcode.css</a> when using 'League'.

Many thanks and have a good day,

Jim

**Comment by denehyg** [comment]
This is currently not supported. When I get some time I'll have a look at adding it.

**Comment by jamespascoe** [comment]
Great - thank you very much - much appreciated.

Thanks again and have a good day.

**Comment by denehyg** [comment]
I just released v2.1.0 to add support for changing the highlight theme. You'll need to provide your specific theme setup in the menu configuration in your presentations. Let me know if you have any issues with it.

**Comment by jamespascoe** [comment]
Great - thank you very much - that's excellent - thanks - I'll give it a go.

Thanks again and take care.
