### ISSUE TITLE
Post source code for demo?

### ISSUE THREAD

**Issue by Gkleinereva** [denehyg/reveal.js-menu#69]
Hey Greg @denehyg -

I'm having trouble getting reveal.js-menu to work inside of an angular application.  Is there any chance you can point folks towards the source code (js config and Reveal raw) for your live demo?  I think it might help me and others to get it working.

Thanks!
Evan

**Comment by denehyg** [comment]
The demo is included in this repo under the gh-pages branch. Start with the index.html file.
