### ISSUE TITLE
Use of cdn for dependencies or compile them to a single file

### ISSUE THREAD

**Issue by dvenkatsagar** [denehyg/reveal.js-menu#9]
I am trying to create a webpage with little bit of navigation using the revealjs and reveal-menu. Im also using bootstrap and font-awesome with it. The thing is I kinda have my font-awesome already installed in the index.html via cdn.

It would be nice if I could use that cdn or some thing that allows me load them only once. Instead of loading one for index.html and one in the menu.js

One idea that I have is to compile all the dependencies in one file and give that out.

**Comment by denehyg** [comment]
Managing dependencies is something that requires more thought, but it is unlikely that a CDN will be used. We have a hard requirement to host presentations offline so I need to package everything we need. Also, the plugin cannot assume the resources it needs are already loaded. For now it is safest to bundle it in the package.

You could always fork to remove font-awesome from the menu, as long as you load it from your pages when you includes the menu - just remove lines 17 and 525 from menu.js.

**Comment by dvenkatsagar** [comment]
Another idea is that it would be good to add some functionality where the developer can add an option like 
```javascript
menu : {
  dependencies : {
    fontawesome : "" // path to font-awesome
   jeesh : "" // path to jeesh
  bowser : "" // path to bowser
  }
}
```

I do know how to do it, and if possible would like to implement it.
